export const Products = [
    {
      id: 1,
      name: 'Product 1',
      price: 100,
      createdAt: new Date(),
    },
    {
      id: 2,
      name: 'Product 2',
      price: 200,
      createdAt: new Date(),
    },
    {
      id: 3,
      name: 'Product 3',
      price: 300,
      createdAt: new Date(),
    },
    {
      id: 4,
      name: 'Product 4',
      price: 400,
      createdAt: new Date(),
    },
    {
      id: 5,
      name: 'Product 5',
      price: 500,
      createdAt: new Date(),
    },
    {
      id: 6,
      name: 'Product 6',
      price: 600,
      createdAt: new Date(),
    },
    {
      id: 7,
      name: 'Product 7',
      price: 700,
      createdAt: new Date(),
    },
    {
      id: 8,
      name: 'Product 8',
      price: 800,
      createdAt: new Date(),
    },
    {
      id: 9,
      name: 'Product 9',
      price: 900,
      createdAt: new Date(),
    },
    {
      id: 10,
      name: 'Product 10',
      price: 1000,
      createdAt: new Date(),
    },
    {
      id: 11,
      name: 'Product 11',
      price: 1100,
      createdAt: new Date(),
    },
    {
      id: 12,
      name: 'Product 12',
      price: 1200,
      createdAt: new Date(),
    },
    {
      id: 13,
      name: 'Product 13',
      price: 1300,
      createdAt: new Date(),
    },
    {
      id: 14,
      name: 'Product 14',
      price: 1400,
      createdAt: new Date(),
    },
    {
      id: 15,
      name: 'Product 15',
      price: 1500,
      createdAt: new Date(),
    },
    {
      id: 16,
      name: 'Product 16',
      price: 1600,
      createdAt: new Date(),
    },
    {
      id: 17,
      name: 'Product 17',
      price: 1700,
      createdAt: new Date(),
    },
    {
      id: 18,
      name: 'Product 18',
      price: 1800,
      createdAt: new Date(),
    },
    {
      id: 19,
      name: 'Product 19',
      price: 1900,
      createdAt: new Date(),
    },
    {
      id: 20,
      name: 'Product 20',
      price: 2000,
      createdAt: new Date(),
    }
  ];